---
version: "3"

networks:
  kafka:
    driver: bridge

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  edge-proxy:
    build: envoy-edge-proxy
    ports:
      - 8080:8080
      - 9000:9000

  http-api:
    build: http-api-amqp-producer
    environment:
      ZIPKIN_URL: http://zipkin:9411/
      RABBIT_HOST: rabbitmq

  amqp-consumer-kafka-producer:
    build: amqp-consumer-kafka-producer
    environment:
      ZIPKIN_URL: http://zipkin:9411/
      RABBIT_HOST: rabbitmq
      KAFKA_URL: kafka:9092
    networks:
     - default
     - kafka

  kafka-consumer-db-writer:
    build: kafka-consumer-db-writer
    environment:
      ZIPKIN_URL: http://zipkin:9411/
      KAFKA_URL: kafka:9092
      DB_URL: jdbc:mysql://db:3306/sample-db?useSSL=false&allowPublicKeyRetrieval=true&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor
      DB_USER: sample-user
      DB_PASSWORD: sample-password
    networks:
     - default
     - kafka

  db:
    image: mysql:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample-db
      MYSQL_USER: sample-user
      MYSQL_PASSWORD: sample-password

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 15672:15672

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka
