---
version: "3"

networks:
  kafka:
    driver: bridge

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  edge-proxy:
    build: envoy-edge-proxy
    ports:
      - 8080:8080
      - 9000:9000

  http-api:
    build: java-spring-rest
    environment:
      ZIPKIN_URL: http://zipkin:9411/
      RABBIT_HOST: rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 15672:15672

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka
