spring:
  application.name: amqp-consumer-kafka-producer
  zipkin:
    baseUrl: ${ZIPKIN_URL}
    sender.type: web

  rabbitmq:
    template:
      exchange: sample-exchange
    host: ${RABBIT_HOST}

  kafka:
    bootstrap-servers: ${KAFKA_URL}
#    client-id: test-client
#    consumer:
#      auto-offset-reset: latest
#      group-id: test-group
#    listener:
#      concurrency: 4